apiVersion: v1
kind: Service
metadata:
  name: labelvision-deployment
spec:
  selector:
    app: labelvision
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: NodePort