artifact_location: file:///C:/Users/aa-dz/OneDrive/Bureau/Master2/11_-_Orchestration/27062024_1856/labelvision-main/labelvision-main/runs/mlflow/0
creation_time: 1719557776927
experiment_id: '0'
last_update_time: 1719557776927
lifecycle_stage: active
name: Default
